name: Example CI/CD

on:
  push:
    paths:
      - 'example/**'
  pull_request:
    paths:
      - 'example/**'

defaults:
  run:
    working-directory: ./example

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install lcov
        run: sudo apt-get install lcov

      - name: Analyzing
        run: flutter analyze

      - name: Running test
        run: flutter test --coverage

      - name: Coverage check
        run: |
          lcov --remove coverage/lcov.info '*.g.dart' '*.part.dart' '*/generated/*' -o coverage/lcov.info
          ../scripts/pana_check.sh
